language: node_js
node_js:
- '8.9.1'
notifications:
  slack:
    secure: mr9OD1fgH3PevZkhmo6DmEjdhsD4e7oS0jUb4a+uWRKpaU3g2DjyJYxwXAMV/clekp0BpQDB1N1KzmvdTicf/Ank+vNqscd0GgpOvOahI3Cmmku7IhVJrzNWi2cvmnvEHbY9ABxOClLtkhmCmpBRovIEq61NtsRGiAGF1valvcFtv26pcNK3KrjXsYTAQdYPvAv27SW8+a+UqyplNKK70eoYzyu9w4/uU/sldmVs6iyFplujxmJXN7A+qY+jT5xqSQ8MAPiRz1N+l4zP/uaBkPfbTcWL8c3wQKUW3I9XWCNlHtA/77BNRINpmCRs5NT6rppsJFu0w4sZFC+4/+eSDYLeqsGXTK+u/Bj1Wu07HMxDzMC3Cm6/a0pbGWuX0xeNHUByIGAGuLWhwblBbbZKfZGzdYHS56YfAXm9ZLyncMxNXXkJ6yx6Tko08mym8GNvnAXPQ+CQLLIOebJ+cnvD5W15PaZ7h/3HcW2Z3ChQFDmhYdbzsjCqLdGIH/PK0UxT+PRkqte+hTbUslMW1t7w1r3OWlC3qW8DFwydbAhGR3YA7qDWcRVslI9gEmu3FwyfM3bZrhEvSRX8aP9HaLHxh7Vuvh9lIlky0hiaKXcGzavWI1dbbgOGg/IZHAI50FbE2Md/YBvMtKpI02EeSe2U75MaOPbLPDEO/nDu2mO0+I0=
sudo: required
services:
  - docker
before_install:
  - docker-compose build
  - docker-compose up -d
script:
  - npm test
